//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PegPayCbApiTester.CbApi {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pegasus.co.ug/", ConfigurationName="CbApi.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/Transact", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PegPayCbApiTester.CbApi.Result Transact(PegPayCbApiTester.CbApi.TransactionRequest tranRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/Transact", ReplyAction="*")]
        System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.Result> TransactAsync(PegPayCbApiTester.CbApi.TransactionRequest tranRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/ReverseTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PegPayCbApiTester.CbApi.Result ReverseTransaction(PegPayCbApiTester.CbApi.TransactionRequest tranRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/ReverseTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.Result> ReverseTransactionAsync(PegPayCbApiTester.CbApi.TransactionRequest tranRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/GetMiniStatement", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PegPayCbApiTester.CbApi.BankAccountStatement GetMiniStatement(string AccountNumber, string BankCode, string Password, PegPayCbApiTester.CbApi.BankCharge[] charges);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/GetMiniStatement", ReplyAction="*")]
        System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.BankAccountStatement> GetMiniStatementAsync(string AccountNumber, string BankCode, string Password, PegPayCbApiTester.CbApi.BankCharge[] charges);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/GetFullStatement", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PegPayCbApiTester.CbApi.BankAccountStatement GetFullStatement(string AccountNumber, string BankCode, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/GetFullStatement", ReplyAction="*")]
        System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.BankAccountStatement> GetFullStatementAsync(string AccountNumber, string BankCode, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/SaveBankAccountDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PegPayCbApiTester.CbApi.Result SaveBankAccountDetails(PegPayCbApiTester.CbApi.BankAccount account, string BankCode, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/SaveBankAccountDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.Result> SaveBankAccountDetailsAsync(PegPayCbApiTester.CbApi.BankAccount account, string BankCode, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/SaveBankDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PegPayCbApiTester.CbApi.Result SaveBankDetails(PegPayCbApiTester.CbApi.Bank bank, string adminUsername, string adminPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/SaveBankDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.Result> SaveBankDetailsAsync(PegPayCbApiTester.CbApi.Bank bank, string adminUsername, string adminPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/SaveBankChargeDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PegPayCbApiTester.CbApi.Result SaveBankChargeDetails(PegPayCbApiTester.CbApi.BankCharge charge, string BankCode, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/SaveBankChargeDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.Result> SaveBankChargeDetailsAsync(PegPayCbApiTester.CbApi.BankCharge charge, string BankCode, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/SaveAccessRule", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PegPayCbApiTester.CbApi.Result SaveAccessRule(PegPayCbApiTester.CbApi.AccessRule rule, string BankCode, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/SaveAccessRule", ReplyAction="*")]
        System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.Result> SaveAccessRuleAsync(PegPayCbApiTester.CbApi.AccessRule rule, string BankCode, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/SaveTransactionRule", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PegPayCbApiTester.CbApi.Result SaveTransactionRule(PegPayCbApiTester.CbApi.TransactionRule rule, string BankCode, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/SaveTransactionRule", ReplyAction="*")]
        System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.Result> SaveTransactionRuleAsync(PegPayCbApiTester.CbApi.TransactionRule rule, string BankCode, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/SaveBankUserDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PegPayCbApiTester.CbApi.Result SaveBankUserDetails(PegPayCbApiTester.CbApi.BankUser user, string BankCode, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/SaveBankUserDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.Result> SaveBankUserDetailsAsync(PegPayCbApiTester.CbApi.BankUser user, string BankCode, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/GetById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PegPayCbApiTester.CbApi.BaseObject GetById(string className, string objectId, string bankCode, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/GetById", ReplyAction="*")]
        System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.BaseObject> GetByIdAsync(string className, string objectId, string bankCode, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/GetAccountSignatories", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PegPayCbApiTester.CbApi.BankCustomer[] GetAccountSignatories(string accountNumber, string bankCode, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/GetAccountSignatories", ReplyAction="*")]
        System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.BankCustomer[]> GetAccountSignatoriesAsync(string accountNumber, string bankCode, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/GetAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PegPayCbApiTester.CbApi.BaseObject[] GetAll(string className, string bankCode, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/GetAll", ReplyAction="*")]
        System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.BaseObject[]> GetAllAsync(string className, string bankCode, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/SaveBankTellerDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PegPayCbApiTester.CbApi.Result SaveBankTellerDetails(PegPayCbApiTester.CbApi.BankTeller teller, string BankCode, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/SaveBankTellerDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.Result> SaveBankTellerDetailsAsync(PegPayCbApiTester.CbApi.BankTeller teller, string BankCode, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/SaveBankBranchDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PegPayCbApiTester.CbApi.Result SaveBankBranchDetails(PegPayCbApiTester.CbApi.BankBranch branch, string BankCode, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/SaveBankBranchDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.Result> SaveBankBranchDetailsAsync(PegPayCbApiTester.CbApi.BankBranch branch, string BankCode, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/SaveUserTypeDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PegPayCbApiTester.CbApi.Result SaveUserTypeDetails(PegPayCbApiTester.CbApi.UserType userType, string BankCode, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/SaveUserTypeDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.Result> SaveUserTypeDetailsAsync(PegPayCbApiTester.CbApi.UserType userType, string BankCode, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/SaveAccountTypeDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PegPayCbApiTester.CbApi.Result SaveAccountTypeDetails(PegPayCbApiTester.CbApi.AccountType accountType, string BankCode, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/SaveAccountTypeDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.Result> SaveAccountTypeDetailsAsync(PegPayCbApiTester.CbApi.AccountType accountType, string BankCode, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/SaveChargeTypeDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PegPayCbApiTester.CbApi.Result SaveChargeTypeDetails(PegPayCbApiTester.CbApi.ChargeType chargeType, string BankCode, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/SaveChargeTypeDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.Result> SaveChargeTypeDetailsAsync(PegPayCbApiTester.CbApi.ChargeType chargeType, string BankCode, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/SaveTransactionCategoryDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PegPayCbApiTester.CbApi.Result SaveTransactionCategoryDetails(PegPayCbApiTester.CbApi.TransactionCategory tranType, string BankCode, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/SaveTransactionCategoryDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.Result> SaveTransactionCategoryDetailsAsync(PegPayCbApiTester.CbApi.TransactionCategory tranType, string BankCode, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/SaveBankCustomerDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PegPayCbApiTester.CbApi.Result SaveBankCustomerDetails(PegPayCbApiTester.CbApi.BankCustomer cust, string BankCode, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/SaveBankCustomerDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.Result> SaveBankCustomerDetailsAsync(PegPayCbApiTester.CbApi.BankCustomer cust, string BankCode, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/SaveCustomerTypeDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PegPayCbApiTester.CbApi.Result SaveCustomerTypeDetails(PegPayCbApiTester.CbApi.CustomerType custType, string BankCode, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/SaveCustomerTypeDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.Result> SaveCustomerTypeDetailsAsync(PegPayCbApiTester.CbApi.CustomerType custType, string BankCode, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/ExecuteNonQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PegPayCbApiTester.CbApi.Result ExecuteNonQuery(string storedProcedureName, string[] Parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/ExecuteNonQuery", ReplyAction="*")]
        System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.Result> ExecuteNonQueryAsync(string storedProcedureName, string[] Parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/ExecuteDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ExecuteDataSet(string storedProcedureName, string[] Parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pegasus.co.ug/ExecuteDataSet", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ExecuteDataSetAsync(string storedProcedureName, string[] Parameters);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pegasus.co.ug/")]
    public partial class TransactionRequest : BaseObject {
        
        private string customerNameField;
        
        private string customerIdField;
        
        private string toAccountField;
        
        private string fromAccountField;
        
        private string tranAmountField;
        
        private string bankTranIdField;
        
        private string paymentDateField;
        
        private string tellerField;
        
        private string approvedByField;
        
        private string bankCodeField;
        
        private string narrationField;
        
        private string passwordField;
        
        private string digitalSignatureField;
        
        private string tranCategoryField;
        
        private string branchCodeField;
        
        private string currencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
                this.RaisePropertyChanged("CustomerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
                this.RaisePropertyChanged("CustomerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ToAccount {
            get {
                return this.toAccountField;
            }
            set {
                this.toAccountField = value;
                this.RaisePropertyChanged("ToAccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FromAccount {
            get {
                return this.fromAccountField;
            }
            set {
                this.fromAccountField = value;
                this.RaisePropertyChanged("FromAccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TranAmount {
            get {
                return this.tranAmountField;
            }
            set {
                this.tranAmountField = value;
                this.RaisePropertyChanged("TranAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string BankTranId {
            get {
                return this.bankTranIdField;
            }
            set {
                this.bankTranIdField = value;
                this.RaisePropertyChanged("BankTranId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string PaymentDate {
            get {
                return this.paymentDateField;
            }
            set {
                this.paymentDateField = value;
                this.RaisePropertyChanged("PaymentDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Teller {
            get {
                return this.tellerField;
            }
            set {
                this.tellerField = value;
                this.RaisePropertyChanged("Teller");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ApprovedBy {
            get {
                return this.approvedByField;
            }
            set {
                this.approvedByField = value;
                this.RaisePropertyChanged("ApprovedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string BankCode {
            get {
                return this.bankCodeField;
            }
            set {
                this.bankCodeField = value;
                this.RaisePropertyChanged("BankCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Narration {
            get {
                return this.narrationField;
            }
            set {
                this.narrationField = value;
                this.RaisePropertyChanged("Narration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string DigitalSignature {
            get {
                return this.digitalSignatureField;
            }
            set {
                this.digitalSignatureField = value;
                this.RaisePropertyChanged("DigitalSignature");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string TranCategory {
            get {
                return this.tranCategoryField;
            }
            set {
                this.tranCategoryField = value;
                this.RaisePropertyChanged("TranCategory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string BranchCode {
            get {
                return this.branchCodeField;
            }
            set {
                this.branchCodeField = value;
                this.RaisePropertyChanged("BranchCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("Currency");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransactionCategory))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ChargeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AccountType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomerType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BankBranch))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BankUser))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BankTeller))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BankCustomer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransactionRule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AccessRule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bank))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BankAccount))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BankCharge))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Result))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BankAccountStatement))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransactionRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pegasus.co.ug/")]
    public partial class BaseObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusCodeField;
        
        private string statusDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("StatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusDesc {
            get {
                return this.statusDescField;
            }
            set {
                this.statusDescField = value;
                this.RaisePropertyChanged("StatusDesc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pegasus.co.ug/")]
    public partial class TransactionCategory : BaseObject {
        
        private string idField;
        
        private string tranCategoryCodeField;
        
        private string tranCategoryNameField;
        
        private string descriptionField;
        
        private string modifiedByField;
        
        private string approvedByField;
        
        private string bankCodeField;
        
        private string isActiveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TranCategoryCode {
            get {
                return this.tranCategoryCodeField;
            }
            set {
                this.tranCategoryCodeField = value;
                this.RaisePropertyChanged("TranCategoryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TranCategoryName {
            get {
                return this.tranCategoryNameField;
            }
            set {
                this.tranCategoryNameField = value;
                this.RaisePropertyChanged("TranCategoryName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
                this.RaisePropertyChanged("ModifiedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ApprovedBy {
            get {
                return this.approvedByField;
            }
            set {
                this.approvedByField = value;
                this.RaisePropertyChanged("ApprovedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string BankCode {
            get {
                return this.bankCodeField;
            }
            set {
                this.bankCodeField = value;
                this.RaisePropertyChanged("BankCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
                this.RaisePropertyChanged("IsActive");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pegasus.co.ug/")]
    public partial class ChargeType : BaseObject {
        
        private string chargeTypeCodeField;
        
        private string chargeTypeNameField;
        
        private string descriptionField;
        
        private string isActiveField;
        
        private string bankCodeField;
        
        private string modifiedByField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ChargeTypeCode {
            get {
                return this.chargeTypeCodeField;
            }
            set {
                this.chargeTypeCodeField = value;
                this.RaisePropertyChanged("ChargeTypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ChargeTypeName {
            get {
                return this.chargeTypeNameField;
            }
            set {
                this.chargeTypeNameField = value;
                this.RaisePropertyChanged("ChargeTypeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
                this.RaisePropertyChanged("IsActive");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string BankCode {
            get {
                return this.bankCodeField;
            }
            set {
                this.bankCodeField = value;
                this.RaisePropertyChanged("BankCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
                this.RaisePropertyChanged("ModifiedBy");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pegasus.co.ug/")]
    public partial class AccountType : BaseObject {
        
        private string idField;
        
        private string accTypeNameField;
        
        private string accTypeCodeField;
        
        private string descriptionField;
        
        private string minimumBalanceField;
        
        private string modifiedByField;
        
        private string bankCodeField;
        
        private string isDebitableField;
        
        private string modifiedOnField;
        
        private string isActiveField;
        
        private int minNumberOfSignatoriesField;
        
        private int maxNumberOfSignatoriesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AccTypeName {
            get {
                return this.accTypeNameField;
            }
            set {
                this.accTypeNameField = value;
                this.RaisePropertyChanged("AccTypeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AccTypeCode {
            get {
                return this.accTypeCodeField;
            }
            set {
                this.accTypeCodeField = value;
                this.RaisePropertyChanged("AccTypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MinimumBalance {
            get {
                return this.minimumBalanceField;
            }
            set {
                this.minimumBalanceField = value;
                this.RaisePropertyChanged("MinimumBalance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
                this.RaisePropertyChanged("ModifiedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string BankCode {
            get {
                return this.bankCodeField;
            }
            set {
                this.bankCodeField = value;
                this.RaisePropertyChanged("BankCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string IsDebitable {
            get {
                return this.isDebitableField;
            }
            set {
                this.isDebitableField = value;
                this.RaisePropertyChanged("IsDebitable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ModifiedOn {
            get {
                return this.modifiedOnField;
            }
            set {
                this.modifiedOnField = value;
                this.RaisePropertyChanged("ModifiedOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
                this.RaisePropertyChanged("IsActive");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int MinNumberOfSignatories {
            get {
                return this.minNumberOfSignatoriesField;
            }
            set {
                this.minNumberOfSignatoriesField = value;
                this.RaisePropertyChanged("MinNumberOfSignatories");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int MaxNumberOfSignatories {
            get {
                return this.maxNumberOfSignatoriesField;
            }
            set {
                this.maxNumberOfSignatoriesField = value;
                this.RaisePropertyChanged("MaxNumberOfSignatories");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomerType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pegasus.co.ug/")]
    public partial class UserType : BaseObject {
        
        private string idField;
        
        private string userTypeNameField;
        
        private string userTypeCodeField;
        
        private string roleField;
        
        private string descriptionField;
        
        private string bankCodeField;
        
        private string isActiveField;
        
        private string modifiedByField;
        
        private string modifiedOnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserTypeName {
            get {
                return this.userTypeNameField;
            }
            set {
                this.userTypeNameField = value;
                this.RaisePropertyChanged("UserTypeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UserTypeCode {
            get {
                return this.userTypeCodeField;
            }
            set {
                this.userTypeCodeField = value;
                this.RaisePropertyChanged("UserTypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
                this.RaisePropertyChanged("Role");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string BankCode {
            get {
                return this.bankCodeField;
            }
            set {
                this.bankCodeField = value;
                this.RaisePropertyChanged("BankCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
                this.RaisePropertyChanged("IsActive");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
                this.RaisePropertyChanged("ModifiedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ModifiedOn {
            get {
                return this.modifiedOnField;
            }
            set {
                this.modifiedOnField = value;
                this.RaisePropertyChanged("ModifiedOn");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pegasus.co.ug/")]
    public partial class CustomerType : UserType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pegasus.co.ug/")]
    public partial class BankBranch : BaseObject {
        
        private string bankBranchIdField;
        
        private string branchNameField;
        
        private string branchCodeField;
        
        private string locationField;
        
        private string bankCodeField;
        
        private string createdOnField;
        
        private string modifiedOnField;
        
        private string createdByField;
        
        private string modifiedByField;
        
        private string isActiveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BankBranchId {
            get {
                return this.bankBranchIdField;
            }
            set {
                this.bankBranchIdField = value;
                this.RaisePropertyChanged("BankBranchId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BranchName {
            get {
                return this.branchNameField;
            }
            set {
                this.branchNameField = value;
                this.RaisePropertyChanged("BranchName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BranchCode {
            get {
                return this.branchCodeField;
            }
            set {
                this.branchCodeField = value;
                this.RaisePropertyChanged("BranchCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("Location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string BankCode {
            get {
                return this.bankCodeField;
            }
            set {
                this.bankCodeField = value;
                this.RaisePropertyChanged("BankCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CreatedOn {
            get {
                return this.createdOnField;
            }
            set {
                this.createdOnField = value;
                this.RaisePropertyChanged("CreatedOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ModifiedOn {
            get {
                return this.modifiedOnField;
            }
            set {
                this.modifiedOnField = value;
                this.RaisePropertyChanged("ModifiedOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("CreatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
                this.RaisePropertyChanged("ModifiedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
                this.RaisePropertyChanged("IsActive");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BankTeller))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BankCustomer))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pegasus.co.ug/")]
    public partial class BankUser : BaseObject {
        
        private string emailField;
        
        private string idField;
        
        private string fullNameField;
        
        private string usertypeField;
        
        private string passwordField;
        
        private string isActiveField;
        
        private string modifiedByField;
        
        private string canHaveAccountField;
        
        private string branchCodeField;
        
        private string dateOfBirthField;
        
        private string phoneNumberField;
        
        private string genderField;
        
        private string bankCodeField;
        
        private string transactionLimitField;
        
        private string pathToProfilePicField;
        
        private string pathToSignatureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
                this.RaisePropertyChanged("FullName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Usertype {
            get {
                return this.usertypeField;
            }
            set {
                this.usertypeField = value;
                this.RaisePropertyChanged("Usertype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
                this.RaisePropertyChanged("IsActive");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
                this.RaisePropertyChanged("ModifiedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CanHaveAccount {
            get {
                return this.canHaveAccountField;
            }
            set {
                this.canHaveAccountField = value;
                this.RaisePropertyChanged("CanHaveAccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string BranchCode {
            get {
                return this.branchCodeField;
            }
            set {
                this.branchCodeField = value;
                this.RaisePropertyChanged("BranchCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string DateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
                this.RaisePropertyChanged("DateOfBirth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
                this.RaisePropertyChanged("PhoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("Gender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string BankCode {
            get {
                return this.bankCodeField;
            }
            set {
                this.bankCodeField = value;
                this.RaisePropertyChanged("BankCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string TransactionLimit {
            get {
                return this.transactionLimitField;
            }
            set {
                this.transactionLimitField = value;
                this.RaisePropertyChanged("TransactionLimit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string PathToProfilePic {
            get {
                return this.pathToProfilePicField;
            }
            set {
                this.pathToProfilePicField = value;
                this.RaisePropertyChanged("PathToProfilePic");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string PathToSignature {
            get {
                return this.pathToSignatureField;
            }
            set {
                this.pathToSignatureField = value;
                this.RaisePropertyChanged("PathToSignature");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pegasus.co.ug/")]
    public partial class BankTeller : BankUser {
        
        private string tellerAccountNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TellerAccountNumber {
            get {
                return this.tellerAccountNumberField;
            }
            set {
                this.tellerAccountNumberField = value;
                this.RaisePropertyChanged("TellerAccountNumber");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pegasus.co.ug/")]
    public partial class BankCustomer : BankUser {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pegasus.co.ug/")]
    public partial class TransactionRule : BaseObject {
        
        private string idField;
        
        private string ruleNameField;
        
        private string ruleCodeField;
        
        private string userIdField;
        
        private string descriptionField;
        
        private string minimumAmountField;
        
        private string maximumAmountField;
        
        private string isActiveField;
        
        private string bankCodeField;
        
        private string branchCodeField;
        
        private string modifiedOnField;
        
        private string modifiedByField;
        
        private string approverField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RuleName {
            get {
                return this.ruleNameField;
            }
            set {
                this.ruleNameField = value;
                this.RaisePropertyChanged("RuleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RuleCode {
            get {
                return this.ruleCodeField;
            }
            set {
                this.ruleCodeField = value;
                this.RaisePropertyChanged("RuleCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string MinimumAmount {
            get {
                return this.minimumAmountField;
            }
            set {
                this.minimumAmountField = value;
                this.RaisePropertyChanged("MinimumAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string MaximumAmount {
            get {
                return this.maximumAmountField;
            }
            set {
                this.maximumAmountField = value;
                this.RaisePropertyChanged("MaximumAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
                this.RaisePropertyChanged("IsActive");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string BankCode {
            get {
                return this.bankCodeField;
            }
            set {
                this.bankCodeField = value;
                this.RaisePropertyChanged("BankCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string BranchCode {
            get {
                return this.branchCodeField;
            }
            set {
                this.branchCodeField = value;
                this.RaisePropertyChanged("BranchCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ModifiedOn {
            get {
                return this.modifiedOnField;
            }
            set {
                this.modifiedOnField = value;
                this.RaisePropertyChanged("ModifiedOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
                this.RaisePropertyChanged("ModifiedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Approver {
            get {
                return this.approverField;
            }
            set {
                this.approverField = value;
                this.RaisePropertyChanged("Approver");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pegasus.co.ug/")]
    public partial class AccessRule : BaseObject {
        
        private string idField;
        
        private string userTypeField;
        
        private string bankCodeField;
        
        private string canAccessField;
        
        private string userIdField;
        
        private string branchCodeField;
        
        private string modifiedOnField;
        
        private string modifiedByField;
        
        private string ruleNameField;
        
        private string isActiveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserType {
            get {
                return this.userTypeField;
            }
            set {
                this.userTypeField = value;
                this.RaisePropertyChanged("UserType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BankCode {
            get {
                return this.bankCodeField;
            }
            set {
                this.bankCodeField = value;
                this.RaisePropertyChanged("BankCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CanAccess {
            get {
                return this.canAccessField;
            }
            set {
                this.canAccessField = value;
                this.RaisePropertyChanged("CanAccess");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string BranchCode {
            get {
                return this.branchCodeField;
            }
            set {
                this.branchCodeField = value;
                this.RaisePropertyChanged("BranchCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ModifiedOn {
            get {
                return this.modifiedOnField;
            }
            set {
                this.modifiedOnField = value;
                this.RaisePropertyChanged("ModifiedOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
                this.RaisePropertyChanged("ModifiedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string RuleName {
            get {
                return this.ruleNameField;
            }
            set {
                this.ruleNameField = value;
                this.RaisePropertyChanged("RuleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
                this.RaisePropertyChanged("IsActive");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pegasus.co.ug/")]
    public partial class Bank : BaseObject {
        
        private string bankIdField;
        
        private string bankNameField;
        
        private string bankCodeField;
        
        private string bankContactEmailField;
        
        private string bankPasswordField;
        
        private string isActiveField;
        
        private string modifiedByField;
        
        private string pathToPublicKeyField;
        
        private string pathToLogoImageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BankId {
            get {
                return this.bankIdField;
            }
            set {
                this.bankIdField = value;
                this.RaisePropertyChanged("BankId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BankName {
            get {
                return this.bankNameField;
            }
            set {
                this.bankNameField = value;
                this.RaisePropertyChanged("BankName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BankCode {
            get {
                return this.bankCodeField;
            }
            set {
                this.bankCodeField = value;
                this.RaisePropertyChanged("BankCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BankContactEmail {
            get {
                return this.bankContactEmailField;
            }
            set {
                this.bankContactEmailField = value;
                this.RaisePropertyChanged("BankContactEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string BankPassword {
            get {
                return this.bankPasswordField;
            }
            set {
                this.bankPasswordField = value;
                this.RaisePropertyChanged("BankPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
                this.RaisePropertyChanged("IsActive");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
                this.RaisePropertyChanged("ModifiedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string PathToPublicKey {
            get {
                return this.pathToPublicKeyField;
            }
            set {
                this.pathToPublicKeyField = value;
                this.RaisePropertyChanged("PathToPublicKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string PathToLogoImage {
            get {
                return this.pathToLogoImageField;
            }
            set {
                this.pathToLogoImageField = value;
                this.RaisePropertyChanged("PathToLogoImage");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pegasus.co.ug/")]
    public partial class BankAccount : BaseObject {
        
        private string accountIdField;
        
        private string accountNumberField;
        
        private string accountBalanceField;
        
        private string userIdField;
        
        private string accountTypeField;
        
        private string bankCodeField;
        
        private string modifiedByField;
        
        private string branchCodeField;
        
        private string isActiveField;
        
        private string[] accountSignatoriesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
                this.RaisePropertyChanged("AccountId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
                this.RaisePropertyChanged("AccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AccountBalance {
            get {
                return this.accountBalanceField;
            }
            set {
                this.accountBalanceField = value;
                this.RaisePropertyChanged("AccountBalance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AccountType {
            get {
                return this.accountTypeField;
            }
            set {
                this.accountTypeField = value;
                this.RaisePropertyChanged("AccountType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string BankCode {
            get {
                return this.bankCodeField;
            }
            set {
                this.bankCodeField = value;
                this.RaisePropertyChanged("BankCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
                this.RaisePropertyChanged("ModifiedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string BranchCode {
            get {
                return this.branchCodeField;
            }
            set {
                this.branchCodeField = value;
                this.RaisePropertyChanged("BranchCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
                this.RaisePropertyChanged("IsActive");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        public string[] AccountSignatories {
            get {
                return this.accountSignatoriesField;
            }
            set {
                this.accountSignatoriesField = value;
                this.RaisePropertyChanged("AccountSignatories");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pegasus.co.ug/")]
    public partial class BankCharge : BaseObject {
        
        private string idField;
        
        private string commissionAccountNumberField;
        
        private string chargeAmountField;
        
        private string transCategoryField;
        
        private string modifiedByField;
        
        private string modifiedOnField;
        
        private string isDebitField;
        
        private string chargeDescriptionField;
        
        private string bankCodeField;
        
        private string chargeNameField;
        
        private string chargeCodeField;
        
        private string isActiveField;
        
        private string accountTypeField;
        
        private string chargeTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CommissionAccountNumber {
            get {
                return this.commissionAccountNumberField;
            }
            set {
                this.commissionAccountNumberField = value;
                this.RaisePropertyChanged("CommissionAccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ChargeAmount {
            get {
                return this.chargeAmountField;
            }
            set {
                this.chargeAmountField = value;
                this.RaisePropertyChanged("ChargeAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TransCategory {
            get {
                return this.transCategoryField;
            }
            set {
                this.transCategoryField = value;
                this.RaisePropertyChanged("TransCategory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
                this.RaisePropertyChanged("ModifiedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ModifiedOn {
            get {
                return this.modifiedOnField;
            }
            set {
                this.modifiedOnField = value;
                this.RaisePropertyChanged("ModifiedOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string IsDebit {
            get {
                return this.isDebitField;
            }
            set {
                this.isDebitField = value;
                this.RaisePropertyChanged("IsDebit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ChargeDescription {
            get {
                return this.chargeDescriptionField;
            }
            set {
                this.chargeDescriptionField = value;
                this.RaisePropertyChanged("ChargeDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string BankCode {
            get {
                return this.bankCodeField;
            }
            set {
                this.bankCodeField = value;
                this.RaisePropertyChanged("BankCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ChargeName {
            get {
                return this.chargeNameField;
            }
            set {
                this.chargeNameField = value;
                this.RaisePropertyChanged("ChargeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ChargeCode {
            get {
                return this.chargeCodeField;
            }
            set {
                this.chargeCodeField = value;
                this.RaisePropertyChanged("ChargeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
                this.RaisePropertyChanged("IsActive");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string AccountType {
            get {
                return this.accountTypeField;
            }
            set {
                this.accountTypeField = value;
                this.RaisePropertyChanged("AccountType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string ChargeType {
            get {
                return this.chargeTypeField;
            }
            set {
                this.chargeTypeField = value;
                this.RaisePropertyChanged("ChargeType");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BankAccountStatement))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pegasus.co.ug/")]
    public partial class Result : BaseObject {
        
        private string requestIdField;
        
        private string pegPayIdField;
        
        private string thirdPartyIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RequestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("RequestId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PegPayId {
            get {
                return this.pegPayIdField;
            }
            set {
                this.pegPayIdField = value;
                this.RaisePropertyChanged("PegPayId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ThirdPartyId {
            get {
                return this.thirdPartyIdField;
            }
            set {
                this.thirdPartyIdField = value;
                this.RaisePropertyChanged("ThirdPartyId");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pegasus.co.ug/")]
    public partial class BankAccountStatement : Result {
        
        private string[] statementField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] statement {
            get {
                return this.statementField;
            }
            set {
                this.statementField = value;
                this.RaisePropertyChanged("statement");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : PegPayCbApiTester.CbApi.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<PegPayCbApiTester.CbApi.ServiceSoap>, PegPayCbApiTester.CbApi.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PegPayCbApiTester.CbApi.Result Transact(PegPayCbApiTester.CbApi.TransactionRequest tranRequest) {
            return base.Channel.Transact(tranRequest);
        }
        
        public System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.Result> TransactAsync(PegPayCbApiTester.CbApi.TransactionRequest tranRequest) {
            return base.Channel.TransactAsync(tranRequest);
        }
        
        public PegPayCbApiTester.CbApi.Result ReverseTransaction(PegPayCbApiTester.CbApi.TransactionRequest tranRequest) {
            return base.Channel.ReverseTransaction(tranRequest);
        }
        
        public System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.Result> ReverseTransactionAsync(PegPayCbApiTester.CbApi.TransactionRequest tranRequest) {
            return base.Channel.ReverseTransactionAsync(tranRequest);
        }
        
        public PegPayCbApiTester.CbApi.BankAccountStatement GetMiniStatement(string AccountNumber, string BankCode, string Password, PegPayCbApiTester.CbApi.BankCharge[] charges) {
            return base.Channel.GetMiniStatement(AccountNumber, BankCode, Password, charges);
        }
        
        public System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.BankAccountStatement> GetMiniStatementAsync(string AccountNumber, string BankCode, string Password, PegPayCbApiTester.CbApi.BankCharge[] charges) {
            return base.Channel.GetMiniStatementAsync(AccountNumber, BankCode, Password, charges);
        }
        
        public PegPayCbApiTester.CbApi.BankAccountStatement GetFullStatement(string AccountNumber, string BankCode, string Password) {
            return base.Channel.GetFullStatement(AccountNumber, BankCode, Password);
        }
        
        public System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.BankAccountStatement> GetFullStatementAsync(string AccountNumber, string BankCode, string Password) {
            return base.Channel.GetFullStatementAsync(AccountNumber, BankCode, Password);
        }
        
        public PegPayCbApiTester.CbApi.Result SaveBankAccountDetails(PegPayCbApiTester.CbApi.BankAccount account, string BankCode, string Password) {
            return base.Channel.SaveBankAccountDetails(account, BankCode, Password);
        }
        
        public System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.Result> SaveBankAccountDetailsAsync(PegPayCbApiTester.CbApi.BankAccount account, string BankCode, string Password) {
            return base.Channel.SaveBankAccountDetailsAsync(account, BankCode, Password);
        }
        
        public PegPayCbApiTester.CbApi.Result SaveBankDetails(PegPayCbApiTester.CbApi.Bank bank, string adminUsername, string adminPassword) {
            return base.Channel.SaveBankDetails(bank, adminUsername, adminPassword);
        }
        
        public System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.Result> SaveBankDetailsAsync(PegPayCbApiTester.CbApi.Bank bank, string adminUsername, string adminPassword) {
            return base.Channel.SaveBankDetailsAsync(bank, adminUsername, adminPassword);
        }
        
        public PegPayCbApiTester.CbApi.Result SaveBankChargeDetails(PegPayCbApiTester.CbApi.BankCharge charge, string BankCode, string Password) {
            return base.Channel.SaveBankChargeDetails(charge, BankCode, Password);
        }
        
        public System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.Result> SaveBankChargeDetailsAsync(PegPayCbApiTester.CbApi.BankCharge charge, string BankCode, string Password) {
            return base.Channel.SaveBankChargeDetailsAsync(charge, BankCode, Password);
        }
        
        public PegPayCbApiTester.CbApi.Result SaveAccessRule(PegPayCbApiTester.CbApi.AccessRule rule, string BankCode, string Password) {
            return base.Channel.SaveAccessRule(rule, BankCode, Password);
        }
        
        public System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.Result> SaveAccessRuleAsync(PegPayCbApiTester.CbApi.AccessRule rule, string BankCode, string Password) {
            return base.Channel.SaveAccessRuleAsync(rule, BankCode, Password);
        }
        
        public PegPayCbApiTester.CbApi.Result SaveTransactionRule(PegPayCbApiTester.CbApi.TransactionRule rule, string BankCode, string Password) {
            return base.Channel.SaveTransactionRule(rule, BankCode, Password);
        }
        
        public System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.Result> SaveTransactionRuleAsync(PegPayCbApiTester.CbApi.TransactionRule rule, string BankCode, string Password) {
            return base.Channel.SaveTransactionRuleAsync(rule, BankCode, Password);
        }
        
        public PegPayCbApiTester.CbApi.Result SaveBankUserDetails(PegPayCbApiTester.CbApi.BankUser user, string BankCode, string Password) {
            return base.Channel.SaveBankUserDetails(user, BankCode, Password);
        }
        
        public System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.Result> SaveBankUserDetailsAsync(PegPayCbApiTester.CbApi.BankUser user, string BankCode, string Password) {
            return base.Channel.SaveBankUserDetailsAsync(user, BankCode, Password);
        }
        
        public PegPayCbApiTester.CbApi.BaseObject GetById(string className, string objectId, string bankCode, string Password) {
            return base.Channel.GetById(className, objectId, bankCode, Password);
        }
        
        public System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.BaseObject> GetByIdAsync(string className, string objectId, string bankCode, string Password) {
            return base.Channel.GetByIdAsync(className, objectId, bankCode, Password);
        }
        
        public PegPayCbApiTester.CbApi.BankCustomer[] GetAccountSignatories(string accountNumber, string bankCode, string Password) {
            return base.Channel.GetAccountSignatories(accountNumber, bankCode, Password);
        }
        
        public System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.BankCustomer[]> GetAccountSignatoriesAsync(string accountNumber, string bankCode, string Password) {
            return base.Channel.GetAccountSignatoriesAsync(accountNumber, bankCode, Password);
        }
        
        public PegPayCbApiTester.CbApi.BaseObject[] GetAll(string className, string bankCode, string Password) {
            return base.Channel.GetAll(className, bankCode, Password);
        }
        
        public System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.BaseObject[]> GetAllAsync(string className, string bankCode, string Password) {
            return base.Channel.GetAllAsync(className, bankCode, Password);
        }
        
        public PegPayCbApiTester.CbApi.Result SaveBankTellerDetails(PegPayCbApiTester.CbApi.BankTeller teller, string BankCode, string Password) {
            return base.Channel.SaveBankTellerDetails(teller, BankCode, Password);
        }
        
        public System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.Result> SaveBankTellerDetailsAsync(PegPayCbApiTester.CbApi.BankTeller teller, string BankCode, string Password) {
            return base.Channel.SaveBankTellerDetailsAsync(teller, BankCode, Password);
        }
        
        public PegPayCbApiTester.CbApi.Result SaveBankBranchDetails(PegPayCbApiTester.CbApi.BankBranch branch, string BankCode, string Password) {
            return base.Channel.SaveBankBranchDetails(branch, BankCode, Password);
        }
        
        public System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.Result> SaveBankBranchDetailsAsync(PegPayCbApiTester.CbApi.BankBranch branch, string BankCode, string Password) {
            return base.Channel.SaveBankBranchDetailsAsync(branch, BankCode, Password);
        }
        
        public PegPayCbApiTester.CbApi.Result SaveUserTypeDetails(PegPayCbApiTester.CbApi.UserType userType, string BankCode, string Password) {
            return base.Channel.SaveUserTypeDetails(userType, BankCode, Password);
        }
        
        public System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.Result> SaveUserTypeDetailsAsync(PegPayCbApiTester.CbApi.UserType userType, string BankCode, string Password) {
            return base.Channel.SaveUserTypeDetailsAsync(userType, BankCode, Password);
        }
        
        public PegPayCbApiTester.CbApi.Result SaveAccountTypeDetails(PegPayCbApiTester.CbApi.AccountType accountType, string BankCode, string Password) {
            return base.Channel.SaveAccountTypeDetails(accountType, BankCode, Password);
        }
        
        public System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.Result> SaveAccountTypeDetailsAsync(PegPayCbApiTester.CbApi.AccountType accountType, string BankCode, string Password) {
            return base.Channel.SaveAccountTypeDetailsAsync(accountType, BankCode, Password);
        }
        
        public PegPayCbApiTester.CbApi.Result SaveChargeTypeDetails(PegPayCbApiTester.CbApi.ChargeType chargeType, string BankCode, string Password) {
            return base.Channel.SaveChargeTypeDetails(chargeType, BankCode, Password);
        }
        
        public System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.Result> SaveChargeTypeDetailsAsync(PegPayCbApiTester.CbApi.ChargeType chargeType, string BankCode, string Password) {
            return base.Channel.SaveChargeTypeDetailsAsync(chargeType, BankCode, Password);
        }
        
        public PegPayCbApiTester.CbApi.Result SaveTransactionCategoryDetails(PegPayCbApiTester.CbApi.TransactionCategory tranType, string BankCode, string Password) {
            return base.Channel.SaveTransactionCategoryDetails(tranType, BankCode, Password);
        }
        
        public System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.Result> SaveTransactionCategoryDetailsAsync(PegPayCbApiTester.CbApi.TransactionCategory tranType, string BankCode, string Password) {
            return base.Channel.SaveTransactionCategoryDetailsAsync(tranType, BankCode, Password);
        }
        
        public PegPayCbApiTester.CbApi.Result SaveBankCustomerDetails(PegPayCbApiTester.CbApi.BankCustomer cust, string BankCode, string Password) {
            return base.Channel.SaveBankCustomerDetails(cust, BankCode, Password);
        }
        
        public System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.Result> SaveBankCustomerDetailsAsync(PegPayCbApiTester.CbApi.BankCustomer cust, string BankCode, string Password) {
            return base.Channel.SaveBankCustomerDetailsAsync(cust, BankCode, Password);
        }
        
        public PegPayCbApiTester.CbApi.Result SaveCustomerTypeDetails(PegPayCbApiTester.CbApi.CustomerType custType, string BankCode, string Password) {
            return base.Channel.SaveCustomerTypeDetails(custType, BankCode, Password);
        }
        
        public System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.Result> SaveCustomerTypeDetailsAsync(PegPayCbApiTester.CbApi.CustomerType custType, string BankCode, string Password) {
            return base.Channel.SaveCustomerTypeDetailsAsync(custType, BankCode, Password);
        }
        
        public PegPayCbApiTester.CbApi.Result ExecuteNonQuery(string storedProcedureName, string[] Parameters) {
            return base.Channel.ExecuteNonQuery(storedProcedureName, Parameters);
        }
        
        public System.Threading.Tasks.Task<PegPayCbApiTester.CbApi.Result> ExecuteNonQueryAsync(string storedProcedureName, string[] Parameters) {
            return base.Channel.ExecuteNonQueryAsync(storedProcedureName, Parameters);
        }
        
        public System.Data.DataSet ExecuteDataSet(string storedProcedureName, string[] Parameters) {
            return base.Channel.ExecuteDataSet(storedProcedureName, Parameters);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ExecuteDataSetAsync(string storedProcedureName, string[] Parameters) {
            return base.Channel.ExecuteDataSetAsync(storedProcedureName, Parameters);
        }
    }
}
