//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4016.
// 
#pragma warning disable 1591

namespace InterLinkClass.PegPayApi {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PegPaySoap", Namespace="http://PegPayPaymentsApi/")]
    public partial class PegPay : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetServerStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTransactionDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryCustomerDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostTransactionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PegPay() {
            this.Url = global::InterLinkClass.Properties.Settings.Default.InterLinkClass_PegPayApi_PegPay;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetServerStatusCompletedEventHandler GetServerStatusCompleted;
        
        /// <remarks/>
        public event GetTransactionDetailsCompletedEventHandler GetTransactionDetailsCompleted;
        
        /// <remarks/>
        public event QueryCustomerDetailsCompletedEventHandler QueryCustomerDetailsCompleted;
        
        /// <remarks/>
        public event PostTransactionCompletedEventHandler PostTransactionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PegPayPaymentsApi/GetServerStatus", RequestNamespace="http://PegPayPaymentsApi/", ResponseNamespace="http://PegPayPaymentsApi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetServerStatus() {
            object[] results = this.Invoke("GetServerStatus", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetServerStatusAsync() {
            this.GetServerStatusAsync(null);
        }
        
        /// <remarks/>
        public void GetServerStatusAsync(object userState) {
            if ((this.GetServerStatusOperationCompleted == null)) {
                this.GetServerStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetServerStatusOperationCompleted);
            }
            this.InvokeAsync("GetServerStatus", new object[0], this.GetServerStatusOperationCompleted, userState);
        }
        
        private void OnGetServerStatusOperationCompleted(object arg) {
            if ((this.GetServerStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetServerStatusCompleted(this, new GetServerStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PegPayPaymentsApi/GetTransactionDetails", RequestNamespace="http://PegPayPaymentsApi/", ResponseNamespace="http://PegPayPaymentsApi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Response GetTransactionDetails(QueryRequest query) {
            object[] results = this.Invoke("GetTransactionDetails", new object[] {
                        query});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void GetTransactionDetailsAsync(QueryRequest query) {
            this.GetTransactionDetailsAsync(query, null);
        }
        
        /// <remarks/>
        public void GetTransactionDetailsAsync(QueryRequest query, object userState) {
            if ((this.GetTransactionDetailsOperationCompleted == null)) {
                this.GetTransactionDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTransactionDetailsOperationCompleted);
            }
            this.InvokeAsync("GetTransactionDetails", new object[] {
                        query}, this.GetTransactionDetailsOperationCompleted, userState);
        }
        
        private void OnGetTransactionDetailsOperationCompleted(object arg) {
            if ((this.GetTransactionDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTransactionDetailsCompleted(this, new GetTransactionDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PegPayPaymentsApi/QueryCustomerDetails", RequestNamespace="http://PegPayPaymentsApi/", ResponseNamespace="http://PegPayPaymentsApi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Response QueryCustomerDetails(QueryRequest query) {
            object[] results = this.Invoke("QueryCustomerDetails", new object[] {
                        query});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void QueryCustomerDetailsAsync(QueryRequest query) {
            this.QueryCustomerDetailsAsync(query, null);
        }
        
        /// <remarks/>
        public void QueryCustomerDetailsAsync(QueryRequest query, object userState) {
            if ((this.QueryCustomerDetailsOperationCompleted == null)) {
                this.QueryCustomerDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryCustomerDetailsOperationCompleted);
            }
            this.InvokeAsync("QueryCustomerDetails", new object[] {
                        query}, this.QueryCustomerDetailsOperationCompleted, userState);
        }
        
        private void OnQueryCustomerDetailsOperationCompleted(object arg) {
            if ((this.QueryCustomerDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryCustomerDetailsCompleted(this, new QueryCustomerDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PegPayPaymentsApi/PostTransaction", RequestNamespace="http://PegPayPaymentsApi/", ResponseNamespace="http://PegPayPaymentsApi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Response PostTransaction(TransactionRequest trans) {
            object[] results = this.Invoke("PostTransaction", new object[] {
                        trans});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void PostTransactionAsync(TransactionRequest trans) {
            this.PostTransactionAsync(trans, null);
        }
        
        /// <remarks/>
        public void PostTransactionAsync(TransactionRequest trans, object userState) {
            if ((this.PostTransactionOperationCompleted == null)) {
                this.PostTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostTransactionOperationCompleted);
            }
            this.InvokeAsync("PostTransaction", new object[] {
                        trans}, this.PostTransactionOperationCompleted, userState);
        }
        
        private void OnPostTransactionOperationCompleted(object arg) {
            if ((this.PostTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostTransactionCompleted(this, new PostTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PegPayPaymentsApi/")]
    public partial class QueryRequest {
        
        private string queryField1Field;
        
        private string queryField2Field;
        
        private string queryField3Field;
        
        private string queryField4Field;
        
        private string queryField5Field;
        
        private string queryField6Field;
        
        private string queryField7Field;
        
        private string queryField8Field;
        
        private string queryField9Field;
        
        private string queryField10Field;
        
        /// <remarks/>
        public string QueryField1 {
            get {
                return this.queryField1Field;
            }
            set {
                this.queryField1Field = value;
            }
        }
        
        /// <remarks/>
        public string QueryField2 {
            get {
                return this.queryField2Field;
            }
            set {
                this.queryField2Field = value;
            }
        }
        
        /// <remarks/>
        public string QueryField3 {
            get {
                return this.queryField3Field;
            }
            set {
                this.queryField3Field = value;
            }
        }
        
        /// <remarks/>
        public string QueryField4 {
            get {
                return this.queryField4Field;
            }
            set {
                this.queryField4Field = value;
            }
        }
        
        /// <remarks/>
        public string QueryField5 {
            get {
                return this.queryField5Field;
            }
            set {
                this.queryField5Field = value;
            }
        }
        
        /// <remarks/>
        public string QueryField6 {
            get {
                return this.queryField6Field;
            }
            set {
                this.queryField6Field = value;
            }
        }
        
        /// <remarks/>
        public string QueryField7 {
            get {
                return this.queryField7Field;
            }
            set {
                this.queryField7Field = value;
            }
        }
        
        /// <remarks/>
        public string QueryField8 {
            get {
                return this.queryField8Field;
            }
            set {
                this.queryField8Field = value;
            }
        }
        
        /// <remarks/>
        public string QueryField9 {
            get {
                return this.queryField9Field;
            }
            set {
                this.queryField9Field = value;
            }
        }
        
        /// <remarks/>
        public string QueryField10 {
            get {
                return this.queryField10Field;
            }
            set {
                this.queryField10Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PegPayPaymentsApi/")]
    public partial class TransactionRequest {
        
        private string postField1Field;
        
        private string postField2Field;
        
        private string postField3Field;
        
        private string postField4Field;
        
        private string postField5Field;
        
        private string postField6Field;
        
        private string postField7Field;
        
        private string postField8Field;
        
        private string postField9Field;
        
        private string postField10Field;
        
        private string postField11Field;
        
        private string postField12Field;
        
        private string postField13Field;
        
        private string postField14Field;
        
        private string postField15Field;
        
        private string postField16Field;
        
        private string postField17Field;
        
        private string postField18Field;
        
        private string postField19Field;
        
        private string postField20Field;
        
        private string postField21Field;
        
        private string postField22Field;
        
        private string postField23Field;
        
        private string postField24Field;
        
        private string postField25Field;
        
        private string postField26Field;
        
        private string postField27Field;
        
        private string postField28Field;
        
        private string postField29Field;
        
        private string postField30Field;
        
        private string postField31Field;
        
        private string postField32Field;
        
        private string postField33Field;
        
        private string postField34Field;
        
        /// <remarks/>
        public string PostField1 {
            get {
                return this.postField1Field;
            }
            set {
                this.postField1Field = value;
            }
        }
        
        /// <remarks/>
        public string PostField2 {
            get {
                return this.postField2Field;
            }
            set {
                this.postField2Field = value;
            }
        }
        
        /// <remarks/>
        public string PostField3 {
            get {
                return this.postField3Field;
            }
            set {
                this.postField3Field = value;
            }
        }
        
        /// <remarks/>
        public string PostField4 {
            get {
                return this.postField4Field;
            }
            set {
                this.postField4Field = value;
            }
        }
        
        /// <remarks/>
        public string PostField5 {
            get {
                return this.postField5Field;
            }
            set {
                this.postField5Field = value;
            }
        }
        
        /// <remarks/>
        public string PostField6 {
            get {
                return this.postField6Field;
            }
            set {
                this.postField6Field = value;
            }
        }
        
        /// <remarks/>
        public string PostField7 {
            get {
                return this.postField7Field;
            }
            set {
                this.postField7Field = value;
            }
        }
        
        /// <remarks/>
        public string PostField8 {
            get {
                return this.postField8Field;
            }
            set {
                this.postField8Field = value;
            }
        }
        
        /// <remarks/>
        public string PostField9 {
            get {
                return this.postField9Field;
            }
            set {
                this.postField9Field = value;
            }
        }
        
        /// <remarks/>
        public string PostField10 {
            get {
                return this.postField10Field;
            }
            set {
                this.postField10Field = value;
            }
        }
        
        /// <remarks/>
        public string PostField11 {
            get {
                return this.postField11Field;
            }
            set {
                this.postField11Field = value;
            }
        }
        
        /// <remarks/>
        public string PostField12 {
            get {
                return this.postField12Field;
            }
            set {
                this.postField12Field = value;
            }
        }
        
        /// <remarks/>
        public string PostField13 {
            get {
                return this.postField13Field;
            }
            set {
                this.postField13Field = value;
            }
        }
        
        /// <remarks/>
        public string PostField14 {
            get {
                return this.postField14Field;
            }
            set {
                this.postField14Field = value;
            }
        }
        
        /// <remarks/>
        public string PostField15 {
            get {
                return this.postField15Field;
            }
            set {
                this.postField15Field = value;
            }
        }
        
        /// <remarks/>
        public string PostField16 {
            get {
                return this.postField16Field;
            }
            set {
                this.postField16Field = value;
            }
        }
        
        /// <remarks/>
        public string PostField17 {
            get {
                return this.postField17Field;
            }
            set {
                this.postField17Field = value;
            }
        }
        
        /// <remarks/>
        public string PostField18 {
            get {
                return this.postField18Field;
            }
            set {
                this.postField18Field = value;
            }
        }
        
        /// <remarks/>
        public string PostField19 {
            get {
                return this.postField19Field;
            }
            set {
                this.postField19Field = value;
            }
        }
        
        /// <remarks/>
        public string PostField20 {
            get {
                return this.postField20Field;
            }
            set {
                this.postField20Field = value;
            }
        }
        
        /// <remarks/>
        public string PostField21 {
            get {
                return this.postField21Field;
            }
            set {
                this.postField21Field = value;
            }
        }
        
        /// <remarks/>
        public string PostField22 {
            get {
                return this.postField22Field;
            }
            set {
                this.postField22Field = value;
            }
        }
        
        /// <remarks/>
        public string PostField23 {
            get {
                return this.postField23Field;
            }
            set {
                this.postField23Field = value;
            }
        }
        
        /// <remarks/>
        public string PostField24 {
            get {
                return this.postField24Field;
            }
            set {
                this.postField24Field = value;
            }
        }
        
        /// <remarks/>
        public string PostField25 {
            get {
                return this.postField25Field;
            }
            set {
                this.postField25Field = value;
            }
        }
        
        /// <remarks/>
        public string PostField26 {
            get {
                return this.postField26Field;
            }
            set {
                this.postField26Field = value;
            }
        }
        
        /// <remarks/>
        public string PostField27 {
            get {
                return this.postField27Field;
            }
            set {
                this.postField27Field = value;
            }
        }
        
        /// <remarks/>
        public string PostField28 {
            get {
                return this.postField28Field;
            }
            set {
                this.postField28Field = value;
            }
        }
        
        /// <remarks/>
        public string PostField29 {
            get {
                return this.postField29Field;
            }
            set {
                this.postField29Field = value;
            }
        }
        
        /// <remarks/>
        public string PostField30 {
            get {
                return this.postField30Field;
            }
            set {
                this.postField30Field = value;
            }
        }
        
        /// <remarks/>
        public string PostField31 {
            get {
                return this.postField31Field;
            }
            set {
                this.postField31Field = value;
            }
        }
        
        /// <remarks/>
        public string PostField32 {
            get {
                return this.postField32Field;
            }
            set {
                this.postField32Field = value;
            }
        }
        
        /// <remarks/>
        public string PostField33 {
            get {
                return this.postField33Field;
            }
            set {
                this.postField33Field = value;
            }
        }
        
        /// <remarks/>
        public string PostField34 {
            get {
                return this.postField34Field;
            }
            set {
                this.postField34Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PegPayPaymentsApi/")]
    public partial class Response {
        
        private string responseField1Field;
        
        private string responseField2Field;
        
        private string responseField3Field;
        
        private string responseField4Field;
        
        private string responseField5Field;
        
        private string responseField6Field;
        
        private string responseField7Field;
        
        private string responseField8Field;
        
        private string responseField9Field;
        
        private string responseField10Field;
        
        private string responseField11Field;
        
        private string responseField12Field;
        
        private string responseField13Field;
        
        /// <remarks/>
        public string ResponseField1 {
            get {
                return this.responseField1Field;
            }
            set {
                this.responseField1Field = value;
            }
        }
        
        /// <remarks/>
        public string ResponseField2 {
            get {
                return this.responseField2Field;
            }
            set {
                this.responseField2Field = value;
            }
        }
        
        /// <remarks/>
        public string ResponseField3 {
            get {
                return this.responseField3Field;
            }
            set {
                this.responseField3Field = value;
            }
        }
        
        /// <remarks/>
        public string ResponseField4 {
            get {
                return this.responseField4Field;
            }
            set {
                this.responseField4Field = value;
            }
        }
        
        /// <remarks/>
        public string ResponseField5 {
            get {
                return this.responseField5Field;
            }
            set {
                this.responseField5Field = value;
            }
        }
        
        /// <remarks/>
        public string ResponseField6 {
            get {
                return this.responseField6Field;
            }
            set {
                this.responseField6Field = value;
            }
        }
        
        /// <remarks/>
        public string ResponseField7 {
            get {
                return this.responseField7Field;
            }
            set {
                this.responseField7Field = value;
            }
        }
        
        /// <remarks/>
        public string ResponseField8 {
            get {
                return this.responseField8Field;
            }
            set {
                this.responseField8Field = value;
            }
        }
        
        /// <remarks/>
        public string ResponseField9 {
            get {
                return this.responseField9Field;
            }
            set {
                this.responseField9Field = value;
            }
        }
        
        /// <remarks/>
        public string ResponseField10 {
            get {
                return this.responseField10Field;
            }
            set {
                this.responseField10Field = value;
            }
        }
        
        /// <remarks/>
        public string ResponseField11 {
            get {
                return this.responseField11Field;
            }
            set {
                this.responseField11Field = value;
            }
        }
        
        /// <remarks/>
        public string ResponseField12 {
            get {
                return this.responseField12Field;
            }
            set {
                this.responseField12Field = value;
            }
        }
        
        /// <remarks/>
        public string ResponseField13 {
            get {
                return this.responseField13Field;
            }
            set {
                this.responseField13Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void GetServerStatusCompletedEventHandler(object sender, GetServerStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetServerStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetServerStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void GetTransactionDetailsCompletedEventHandler(object sender, GetTransactionDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTransactionDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTransactionDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void QueryCustomerDetailsCompletedEventHandler(object sender, QueryCustomerDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryCustomerDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryCustomerDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void PostTransactionCompletedEventHandler(object sender, PostTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591